# Generated by Django 4.2 on 2025-06-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название плейлиста')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание плейлиста')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='playlist.playlist', verbose_name='Плейлист')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня плейлиста',
                'verbose_name_plural': 'Песни плейлиста',
            },
        ),
    ]
