# Generated by Django 4.2 on 2025-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('playlist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='playlist.PlaylistSong', to='song.song', verbose_name='Песни в плейлисте'),
        ),
    ]
