# Generated by Django 4.2 on 2025-06-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_artists'),
        ('playlist', '0002_playlistsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='song.song', verbose_name='Песня'),
        ),
    ]
