# Generated by Django 4.2 on 2025-06-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlist_songs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ('id',), 'verbose_name': 'Песня плейлиста', 'verbose_name_plural': 'Песни плейлиста'},
        ),
    ]
