# Generated by Django 4.2 on 2025-06-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0003_alter_playlistsong_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='author',
        ),
        migrations.AddField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор плейлиста'),
            preserve_default=False,
        ),
    ]
