# Generated by Django 4.2 on 2025-06-20 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_artists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0004_remove_playlistsong_author_playlist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Автор плейлиста'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='playlist.playlist', verbose_name='Плейлист'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня'),
        ),
    ]
