# Generated by Django 4.2 on 2025-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlistsong_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='default_images/default playlist cover.jpg', upload_to='playlists_avatars/', verbose_name='Аватар плейлиста'),
        ),
    ]
