# Generated by Django 4.2 on 2025-06-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_playlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='image',
            new_name='cover',
        ),
    ]
