# Generated by Django 4.2 on 2026-03-08 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0006_rename_image_playlist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsong',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='playlist.playlist', verbose_name='Название плейлиста'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Название песни'),
        ),
        migrations.CreateModel(
            name='RatedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Оценка плейлиста')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist', verbose_name='Плейлист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка плейлиста',
                'verbose_name_plural': 'Оценка плейлистов',
                'abstract': False,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.CreateModel(
            name='FavouritePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist', verbose_name='Плейлист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Любимый плейлист',
                'verbose_name_plural': 'Любимые плейлисты',
                'abstract': False,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddConstraint(
            model_name='ratedplaylist',
            constraint=models.UniqueConstraint(fields=('user', 'playlist'), name='unique_ratedplaylist'),
        ),
        migrations.AddConstraint(
            model_name='favouriteplaylist',
            constraint=models.UniqueConstraint(fields=('user', 'playlist'), name='unique_favouriteplaylist'),
        ),
    ]
