# Generated by Django 4.2 on 2025-06-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Имя артиста')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Краткие сведения об артисте')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artist_avatars/', verbose_name='Изображение исполнителя')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Жанр автора',
                'verbose_name_plural': 'Жанры авторов',
            },
        ),
        migrations.CreateModel(
            name='RelatedArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_artists', to='artist.artist', verbose_name='Артист')),
                ('related_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Похожий артист')),
            ],
            options={
                'verbose_name': 'Похожий исполнитель',
                'verbose_name_plural': 'Похожие исполнители',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='song_artists', to='artist.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель песни',
                'verbose_name_plural': 'Исполнители песни',
            },
        ),
    ]
