# Generated by Django 4.2 on 2025-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Имя артиста')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Краткие сведения об артисте')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artist_avatars/', verbose_name='Изображение исполнителя')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ('id',),
            },
        ),
    ]
