# Generated by Django 4.2 on 2025-06-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_artists', to='artist.artist', verbose_name='Артист')),
                ('related_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_artists', to='artist.artist', verbose_name='Похожий артист')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre', verbose_name='Жанр, в котором автор работает')),
            ],
            options={
                'verbose_name': 'Жанр автора',
                'verbose_name_plural': 'Жанры авторов',
            },
        ),
    ]
