# Generated by Django 4.2 on 2025-06-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('artist', '0001_initial'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='song.song', verbose_name='Песня'),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres', to='artist.artist', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre', verbose_name='Жанр, в котором автор работает'),
        ),
    ]
