# Generated by Django 4.2 on 2025-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_favouritealbum_options_and_more'),
        ('artist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(through='albums.AlbumArtist', to='albums.album'),
        ),
    ]
