# Generated by Django 4.2 on 2025-06-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_relatedartists_artistgenre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('id',), 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='relatedartists',
            options={'ordering': ('id',), 'verbose_name': 'Похожий исполнитель', 'verbose_name_plural': 'Похожие исполнители'},
        ),
    ]
