# Generated by Django 4.2 on 2025-06-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_options_alter_relatedartists_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Краткие сведения об артисте'),
        ),
    ]
