# Generated by Django 4.2 on 2025-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(default='default_images/default artist avatar.png', upload_to='artist_avatars/', verbose_name='Изображение исполнителя'),
        ),
    ]
