# Generated by Django 4.2 on 2026-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_genre_albums'),
        ('artist', '0004_alter_artist_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(through='artist.ArtistGenre', to='genre.genre'),
        ),
    ]
