# Generated by Django 4.2 on 2025-06-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('artist', '0004_alter_artist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artist.artist', verbose_name='Исполнитель')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='song.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Исполнитель песни',
                'verbose_name_plural': 'Исполнители песни',
            },
        ),
    ]
