# Generated by Django 4.2 on 2025-06-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_name'),
        ('song', '0001_initial'),
        ('artist', '0005_artistsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres', to='genre.genre', verbose_name='Жанр, в котором автор работает'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='song_artists', to='song.song', verbose_name='Песня'),
        ),
        migrations.AlterField(
            model_name='relatedartists',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='relatedartists',
            name='related_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_artists', to='artist.artist', verbose_name='Похожий артист'),
        ),
    ]
