# Generated by Django 4.2 on 2026-03-12 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0002_alter_song_options'),
        ('artist', '0005_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsong',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artists', to='artist.artist', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня'),
        ),
        migrations.CreateModel(
            name='FavouriteArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Исполнитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_artists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Любимый исполнитель',
                'verbose_name_plural': 'Любимые исполнители',
            },
        ),
    ]
