# Generated by Django 4.2 on 2026-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_alter_artistsong_artist_alter_artistsong_song_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouriteartist',
            constraint=models.UniqueConstraint(fields=('user', 'artist'), name='unique_favouriteartist'),
        ),
    ]
