# Generated by Django 4.2 on 2025-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_artists_alter_album_cover'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='albums',
            field=models.ManyToManyField(through='albums.AlbumGenre', to='albums.album'),
        ),
    ]
