# Generated by Django 4.2 on 2026-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_genres'),
        ('genre', '0002_genre_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='artists',
            field=models.ManyToManyField(through='artist.ArtistGenre', to='artist.artist'),
        ),
    ]
