# Generated by Django 4.2 on 2026-03-14 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genre', '0003_genre_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre', verbose_name='Жанр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_genres', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Любимый жанр',
                'verbose_name_plural': 'Любимые жанры',
            },
        ),
        migrations.AddConstraint(
            model_name='favouritegenre',
            constraint=models.UniqueConstraint(fields=('user', 'genre'), name='unique_favouritegenre'),
        ),
    ]
