# Generated by Django 4.2 on 2025-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название альбома')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации альбома')),
            ],
        ),
    ]
