# Generated by Django 4.2 on 2025-06-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название альбома')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации альбома')),
                ('cover', models.ImageField(upload_to='album_covers/', verbose_name='Обложка альбома')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Автор альбома',
                'verbose_name_plural': 'Авторы альбома',
            },
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Жанр альбома',
                'verbose_name_plural': 'Жанры альбома',
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Песня с альбома',
                'verbose_name_plural': 'Песни альбома',
            },
        ),
        migrations.CreateModel(
            name='FavouriteAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Любимый альбом',
                'verbose_name_plural': 'Любимые альбомы',
            },
        ),
        migrations.CreateModel(
            name='ListenedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Прослушанный альбом',
                'verbose_name_plural': 'Прослушанные альбомы',
            },
        ),
        migrations.CreateModel(
            name='RatedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Оценка альбома')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Оценка альбома',
                'verbose_name_plural': 'Оценки альбомов',
            },
        ),
    ]
