# Generated by Django 4.2 on 2025-06-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
        ('song', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='listenedalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='listenedalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='favouritealbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='favouritealbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='albumsong',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='albumsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня'),
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genres', to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='albumartist',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='albumartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artists', to='artist.artist', verbose_name='Артист'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(through='albums.AlbumArtist', to='artist.artist', verbose_name='Исполнители, принявшие участие в альбоме'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(through='albums.AlbumGenre', to='genre.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='albums.AlbumSong', to='song.song', verbose_name='Песни альбома'),
        ),
    ]
