# Generated by Django 4.2 on 2025-06-11 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0001_initial'),
        ('artist', '0001_initial'),
        ('genre', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUserAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('id',), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.CreateModel(
            name='FavouriteAlbum',
            fields=[
                ('abstractuseralbummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='albums.abstractuseralbummodel')),
            ],
            options={
                'verbose_name': 'Любимый альбом',
                'verbose_name_plural': 'Любимые альбомы',
            },
            bases=('albums.abstractuseralbummodel',),
        ),
        migrations.CreateModel(
            name='ListenedAlbum',
            fields=[
                ('abstractuseralbummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='albums.abstractuseralbummodel')),
            ],
            options={
                'verbose_name': 'Прослушанный альбом',
                'verbose_name_plural': 'Прослушанные альбомы',
            },
            bases=('albums.abstractuseralbummodel',),
        ),
        migrations.CreateModel(
            name='RatedAlbum',
            fields=[
                ('abstractuseralbummodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='albums.abstractuseralbummodel')),
                ('rating', models.FloatField(verbose_name='Оценка альбома')),
            ],
            options={
                'verbose_name': 'Оценка альбома',
                'verbose_name_plural': 'Оценки альбомов',
            },
            bases=('albums.abstractuseralbummodel',),
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня с альбома',
                'verbose_name_plural': 'Песни альбома',
            },
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр альбома',
                'verbose_name_plural': 'Жанры альбома',
            },
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Автор альбома',
                'verbose_name_plural': 'Авторы альбома',
            },
        ),
        migrations.AddField(
            model_name='abstractuseralbummodel',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='abstractuseralbummodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
