# Generated by Django 4.2 on 2025-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_abstractuseralbummodel_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='', upload_to='album_covers/', verbose_name='Обложка альбома'),
            preserve_default=False,
        ),
    ]
