# Generated by Django 4.2 on 2025-06-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratedalbum',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Оценка альбома', 'verbose_name_plural': 'Оценки альбомов'},
        ),
        migrations.AddConstraint(
            model_name='ratedalbum',
            constraint=models.UniqueConstraint(fields=('user', 'album'), name='unique_ratedalbum'),
        ),
    ]
