# Generated by Django 4.2 on 2025-06-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_ratedalbum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritealbum',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Любимый альбом', 'verbose_name_plural': 'Любимые альбомы'},
        ),
        migrations.AlterModelOptions(
            name='listenedalbum',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Прослушанный альбом', 'verbose_name_plural': 'Прослушанные альбомы'},
        ),
        migrations.AddConstraint(
            model_name='favouritealbum',
            constraint=models.UniqueConstraint(fields=('user', 'album'), name='unique_favouritealbum'),
        ),
        migrations.AddConstraint(
            model_name='listenedalbum',
            constraint=models.UniqueConstraint(fields=('user', 'album'), name='unique_listenedalbum'),
        ),
    ]
