# Generated by Django 4.2 on 2025-06-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_name'),
        ('artist', '0005_artistsong'),
        ('song', '0001_initial'),
        ('albums', '0003_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(through='albums.AlbumArtist', to='artist.artist', verbose_name='Исполнители, принявшие участие в альбоме'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(through='albums.AlbumGenre', to='genre.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='albums.AlbumSong', to='song.song', verbose_name='Песни альбома'),
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artists', to='artist.artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='albumgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genres', to='genre.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='song.song', verbose_name='Песня'),
        ),
    ]
