# Generated by Django 4.2 on 2025-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_avatar'),
        ('albums', '0004_alter_favouritealbum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='artist_albums', through='albums.AlbumArtist', to='artist.artist', verbose_name='Исполнители, принявшие участие в альбоме'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='default_images/default album cover.jpg', upload_to='album_covers/', verbose_name='Обложка альбома'),
        ),
    ]
