# Generated by Django 4.2 on 2025-06-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_name'),
        ('song', '0002_song_artists'),
        ('albums', '0004_album_artists_album_genres_album_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumgenre',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genres', to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='albumgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='albums.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня'),
        ),
    ]
