# Generated by Django 4.2 on 2026-03-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0005_alter_album_artists_alter_album_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='Альбом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Альбом к прослушиванию',
                'verbose_name_plural': 'Альбомы к прослушиванию',
                'abstract': False,
                'default_related_name': '%(class)ss',
            },
        ),
        migrations.AddConstraint(
            model_name='wishlistalbum',
            constraint=models.UniqueConstraint(fields=('user', 'album'), name='unique_wishlistalbum'),
        ),
    ]
