# Generated by Django 4.2 on 2025-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название песни')),
                ('duration', models.TimeField(verbose_name='Длительность песни')),
                ('artists', models.ManyToManyField(through='artist.ArtistSong', to='artist.artist')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ('-name',),
            },
        ),
    ]
