# Generated by Django 4.2 on 2025-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_alter_artistgenre_genre_alter_artistsong_song_and_more'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='artist.ArtistSong', to='artist.artist'),
        ),
    ]
