# Generated by Django 4.2 on 2026-03-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('id',), 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
    ]
