# Generated by Django 4.2 on 2026-03-16 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0002_alter_song_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Оценка')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song', verbose_name='Песня')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка песни',
                'verbose_name_plural': 'Оценки песни',
            },
        ),
        migrations.AddConstraint(
            model_name='ratedsong',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_ratedsong'),
        ),
    ]
