# Generated by Django 4.2 on 2026-03-16 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_ratedsong_ratedsong_unique_ratedsong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratedsong',
            options={'verbose_name': 'Оценка песни', 'verbose_name_plural': 'Оценки песен'},
        ),
        migrations.AlterField(
            model_name='ratedsong',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Оценка'),
        ),
    ]
