openapi: '3.0.3'
info:
  title: Musicgram API
  version: '1.0'
servers:
  - url: https://api.server.test/v1

components:
  schemas:
    CustomUserCreate:
      type: object
      properties:
        property:
          type: integer
    CustomUserResponseOnCreate:
      type: object
      properties:
        property:
          type: integer
    TokenCreate:
      type: object
      properties:
        property:
          type: integer
    TokenGetResponse:
      type: object
      properties:
        property:
          type: integer
  responses:
    ValidationError:
      description: ''
      content:
        application/json:
          schema: {}
    AuthenticationError:
      description: ''
      content:
        application/json:
          schema: {}
paths:
  /api/users/:
    post:
      description: 'Регистрация нового пользователя'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUserCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUserResponseOnCreate'
          description: 'Пользователь успешно создан'
        '400':
          $ref: '#/components/responses/ValidationError'
  /api/auth/token/login/:
    post:
      operationId: Получить токен авторизации
      description: Используется для авторизации по емейлу и паролю, чтобы далее использовать токен при запросах.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenCreate'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenGetResponse'
          description: ''
  /api/auth/token/logout/:
    post:
      operationId: Удаление токена
      description: Удаляет токен текущего пользователя
      parameters: []
      security:
        - Token: []
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        '204':
          content:
            application/json:
              schema: {}
          description: ''
        '401':
          $ref: '#/components/responses/AuthenticationError'
  