# Generated by Django 4.2 on 2026-03-18 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0006_wishlistalbum_wishlistalbum_unique_wishlistalbum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок рецензии')),
                ('text', models.TextField(blank=True, verbose_name='Текст рецензии')),
                ('type', models.CharField(choices=[('Положительная', 'Positive'), ('Негативная', 'Negative'), ('Нейтральная', 'Neutral')], verbose_name='Тип рецензии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания рецензии')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления рецензии')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='albums.album', verbose_name='Рецензируемый альбом')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецензии')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
            },
        ),
    ]
