# Generated by Django 4.2 on 2026-03-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_alter_review_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('useful', 'Полезно'), ('not_useful', 'Не полезно')], max_length=20, verbose_name='Реакция на рецензию')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review', verbose_name='Рецензия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на рецензию',
                'verbose_name_plural': 'Реакции на рецензию',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewuservote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_reviewuservote'),
        ),
    ]
