# Generated by Django 4.2 on 2026-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewuservote_reviewuservote_unique_reviewuservote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuservote',
            name='reaction',
            field=models.CharField(choices=[('useful', 'Useful'), ('not_useful', 'Not Useful')], max_length=20, verbose_name='Реакция на рецензию'),
        ),
    ]
