# Generated by Django 4.2 on 2026-03-23 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0005_alter_reviewuservote_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('minus', 'Minus'), ('plus', 'Plus')], max_length=20, verbose_name='Реакция на комментарий')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewcomment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на комментарий',
                'verbose_name_plural': 'Реакции на комментарий',
            },
        ),
        migrations.AddConstraint(
            model_name='commentuservote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_commentuservote'),
        ),
    ]
