# Generated by Django 4.2 on 2025-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_images/default user avatar.png', upload_to='user_avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
